### ISSUE TITLE
there is no "Sample" aspect in repository

### ISSUE THREAD

**Issue by zhasik92** [keensoft/alfresco-datalist-constraints#2]
Hi!

I can't to reproduce step 7.

Ho to add Sample aspect?
There is not any aspects in your model

**Comment by angelborroy-ks** [comment]
Use release 2.0.0 to follow the demo, it has been skipped in 2.1.0

https://github.com/keensoft/alfresco-datalist-constraints/blob/2.0.0/datalist-model-repo/src/main/amp/config/alfresco/extension/model/datalist-model.xml
