### ISSUE TITLE
it is not taking values include "&" in it.

### ISSUE THREAD

**Issue by monicakumari** [keensoft/alfresco-datalist-constraints#3]
I have created a datalist which contains an item named "abc & xyz". it was created successfully and was able to see it in dropdown list. 
I have selected the value "abc & xyz" from the dropdown and saved it. 
but on the share site, the value is showing just "abc" instead of "abc & xyz" to user as properties.
It is not taking "&", even I am able to search files with "&".

being a developer, what should I do ?

PFA .
![screenshot from 2017-09-04 11-42-56](https://user-images.githubusercontent.com/26789477/30013830-6f4fa510-9166-11e7-85e1-0f5ee6557bf5.png)
![screenshot from 2017-09-04 11-43-30](https://user-images.githubusercontent.com/26789477/30013832-72680d78-9166-11e7-9fb7-650fa45b3618.png)

thanks in advance.

**Comment by mikelasla** [comment]
Hi, 
I've done some tests and i can persist values with "&" and then show them on Share without problem.

Can you confirm that you chose "Options"  as list type and that **both** code and value have "abc & abc" literal?

Regards

**Comment by monicakumari** [comment]
I have created a level 1 list oth the name "Company Name List".  Then added
new item of label and value with the name "abc & xyz".
I am able to see this item in dropdown. I selected this value and saved the
file.
On the share site. It cuts the value from "&" to end.
I have checked this with multiple values and multiple lists. But same
issue. It prints the value till it finds "&".


Thanks,
Monica

**Comment by mikelasla** [comment]
Hi,

Ok,
Can you see the correct value persisted in the node throught the node browser? let's see if you can at least locate in which side you got the problem, as we can't reproduce it

**Comment by monicakumari** [comment]
okay, can you please tell me In which part of the code I should check for this issue ?

**Comment by monicakumari** [comment]
I have checked using node browser. 
on the node browser, value is "abc & abc"
![screenshot from 2017-09-06 17-06-48](https://user-images.githubusercontent.com/26789477/30110194-dc76af8c-9326-11e7-9af5-aa7b72b7fb9c.png)

but on the share side, it still showing "abc".
![screenshot from 2017-09-04 11-43-30](https://user-images.githubusercontent.com/26789477/30110241-08511034-9327-11e7-8d16-125b49639bb1.png)

**Comment by monicakumari** [comment]
It is showing the whole value "abc & xyz" on share side, if the label is "abc & xyz" and the value is "abc and xyz" or it is without any "&".
![screenshot from 2017-09-06 17-23-04](https://user-images.githubusercontent.com/26789477/30110600-42e6e434-9328-11e7-86d0-5d8b86c2601a.png)

![screenshot from 2017-09-06 17-22-46](https://user-images.githubusercontent.com/26789477/30110606-4833fcf6-9328-11e7-9580-362f0e050306.png)

**Comment by mikelasla** [comment]
Ok
It looks wierd to me, when I create a list of type Options, I can see "code" and "value" columns, you have "Level 1 Value" and "Level 1 Label". Also, i can create that very same value without a problem, so you may be facing an encoding issue somewhere between your database, repo and share?

btw, "code" column is used as label in the dropdown list, "value" is the persisted value. 

Could you tell us some details about your Alfresco installation, like Alfresco version, SO, addon version and so on?

Regards

**Comment by mikelasla** [comment]
Also your share-config would be helpful

**Comment by monicakumari** [comment]
I have made some changes according to our need. can you please help in this ? do you have any idea why this is happening and where should I check for this issue ?

**Comment by angelborroy-ks** [comment]
Use the addon as is and test if it works properly. If so, the problem is in your customisation.
